### ISSUE TITLE
undefined is not an object (evaluating 'n.hasOwnProperty')

### ISSUE THREAD

**Issue by jerson** [yamill/react-native-orientation#132]
Error removingListener

http://crashes.to/s/0c3f1b64e22

```
Fatal Exception: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'n.hasOwnProperty'), stack:
o@687:42
removeOrientationListener@687:880
value@686:1063
value@434:3305
unmountComponent@139:3624
unmountComponent@130:442
unmountComponent@139:3671
unmountComponent@130:442
unmountChildren@137:828
unmountChildren@135:2319
unmountComponent@115:348
unmountComponent@130:442
unmountChildren@137:828
unmountChildren@135:2319
unmountComponent@115:348
unmountComponent@130:442
unmountComponent@139:3671
unmountComponent@130:442
unmountComponent@139:3671
unmountComponent@130:442
unmountComponentFromNode@224:1571
unmountComponentAtNode@224:1467
unmountComponentAtNodeAndRemoveContainer@224:1225
unmountApplicationComponentAtRootTag@317:1105
value@53:2818
<unknown>@53:1053
d@53:127
value@53:1025

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by mayaa6** [comment]
Save problem

**Comment by andrerfneves** [comment]
@jerson @mayaa6 have you tried with latest package v2.0.0?

**Comment by andrerfneves** [comment]
Closing this for now.
