### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by olitomas** [yamill/react-native-orientation#16]
Update the readme to include Android setup ( if it is supported that is ? )

**Comment by yamill** [comment]
No android support as of now. If someone can do a PR for this I will accept it :)

**Comment by jaysoo** [comment]
I created a pull request here https://github.com/yamill/react-native-orientation/pull/22.

I've tested it against react-native 0.16.0 with Nexus 6 emulator and my OnePlus One.

You can lock, unlock, detect orientation changes, just like the iOS version.

**Comment by yamill** [comment]
Awesome! Thanks @jaysoo! :clap:

**Comment by scgough** [comment]
Hi there,
I've got this component set up and running in an app on a Samsung Galaxy S3. I'm getting strange results from it. 100's of LANDSCAPE orientations logged and maybe one PORTRAIT no matter how I hold my phone. 

    componentDidMount: function(){
        Orientation.lockToPortrait();
        Orientation.addOrientationListener(this._orientationDidChange);
    },

    _orientationDidChange: function(orientation){
        console.log("data:", orientation);
        if(orientation == 'LANDSCAPE'){
          console.log("Orientation Landscape")
        }else{
          console.log("Orientation Portrait")
        }
        
    },

    componentWillUnmount: function() {
        Orientation.getOrientation((err,orientation)=> {
            console.log("Current Device Orientation: ", orientation);
        });
        Orientation.removeOrientationListener(this._orientationDidChange);
    },

**Comment by yamill** [comment]
@scgough I believe @vitaminwater fixed this. I just pushed the update to npm, can you try again?

**Comment by scgough** [comment]
Thanks @yamill 
Testing at the moment but I'm initially getting the following compile errors in `OrientationModule.java`

    Error:(34, 15) error: cannot find symbol class BroadcastReceiver
    Error:(34, 48) error: cannot find symbol class BroadcastReceiver
    Error:(51, 49) error: cannot find symbol class IntentFilter
    Error:(56, 57) error: cannot find symbol class IntentFilter

**Comment by vitaminwater** [comment]
Oups, let me fix this.

**Comment by vitaminwater** [comment]
Just made a pull request.

**Comment by yamill** [comment]
Thanks @vitaminwater :+1: 

@scgough I just pushed it again to npm

**Comment by scgough** [comment]
Thanks @yamill @vitaminwater 
This compiles now but I'm getting intermittent crashes. I'm not sure why yet but will continue to investigate. I can see the orientation being logged on the ReactJS side at the point of load and also the further changes are logged on the Java side but when I then switch the phone to the opp. orientation it crashes. 
#weird

**Comment by vitaminwater** [comment]
Can you copy/paste the stacktrace ?

**Comment by scgough** [comment]
I'm seeing this error in Android Studio:

    01-06 17:52:12.459 14400-14400/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.IllegalArgumentException: Receiver not registered: com.github.yamill.orientation.OrientationModule$1@427db3c0
                                                       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:667)
                                                       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1743)
                                                       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:475)
                                                       at com.github.yamill.orientation.OrientationModule$2.onHostDestroy(OrientationModule.java:63)
                                                       at com.facebook.react.bridge.ReactContext.onDestroy(ReactContext.java:160)
                                                       at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:595)
                                                       at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:78)
                                                       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:161)
                                                       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:586)
                                                       at android.os.AsyncTask.execute(AsyncTask.java:534)
                                                       at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:526)
                                                       at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:510)
                                                       at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:78)
                                                       at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:114)
                                                       at com.facebook.react.devsupport.DevSupportManager$15$1.run(DevSupportManager.java:575)
                                                       at android.os.Handler.handleCallback(Handler.java:730)
                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                       at android.os.Looper.loop(Looper.java:176)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by vitaminwater** [comment]
I remember seeing this, but I can't remember what it was:/ Still searching.

Did you add:

```
android:configChanges="keyboardHidden|orientation|screenSize"
```

to you activity in the AndroidManifest.xml ?

**Comment by vitaminwater** [comment]
ok, looks like the issue happens when android calls both onPause and onDestroy.

only fix I got now is to wrap the `unregisterReceiver` calls on `try {} catch` block :/

**Comment by jaysoo** [comment]
@vitaminwater It could be worth keeping a boolean flag to track whether the receiver has been registered or not.

https://github.com/facebook/react-native/blob/5b3cb05fa8b1d100dff15af2bb63c2cfe5e0d17a/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevSupportManager.java#L681-L684

Maybe host was not resumed before pause or destroy is called?

We can still keep the try catch, but it would be a good idea to use FLog to log out the errors.

e.g. https://github.com/facebook/react-native/blob/c45bb3e9c96f4eb4ad8c7af0abac9d5f81e488ee/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L113-L116

**Comment by vitaminwater** [comment]
@jaysoo yes, you are right, I'll go for the FLog option then.

**Comment by scgough** [comment]
Hi everyone - I don't have `android:configChanges="keyboardHidden|orientation|screenSize"` in my manifest file but I can add that if needed?

I will also manually add in the `try/catch` for now to see if it resolves the issue

**Comment by scgough** [comment]
Hi guys,
I've managed to get this working by adding the `try/catch` to the `OrientationModule.java` file (see code below). 
The only issue is that the callback to the React JS seems to have stopped working now. This isn't a massive issue for me as I just need to lock to portrait/landscape at the desired time (which does work) but I thought you should know. 

    ...
    LifecycleEventListener listener = new LifecycleEventListener() {
            @Override
            public void onHostResume() {
                activity.registerReceiver(receiver, new IntentFilter("onConfigurationChanged"));
            }

            @Override
            public void onHostPause() {
                try { activity.unregisterReceiver(receiver); } catch(Exception e) {}
            }

            @Override
            public void onHostDestroy() {
                try { activity.unregisterReceiver(receiver); } catch(Exception e) {}
            }
        };
    ...

**Comment by vitaminwater** [comment]
Ok, just made a PR.

**Comment by yamill** [comment]
Thanks just pushed this to npm

**Comment by bacancy-swaroopa** [comment]
@scgough Hi I am gettting the same error now the app is getting crashed in android

version:

"react-native-orientation": "git+https://github.com/jedt/react-native-orientation.git",
  "react": "^16.0.0-alpha.6",
    "react-native": "^0.43.3",

Did you find any solution to it ?
