### ISSUE TITLE
Android crash after resuming app

### ISSUE THREAD

**Issue by Maydar** [yamill/react-native-orientation#211]
Sometime, application crashes when I resume it.

OS: Android 5.1

Stacktrace:

java.l
ang.RuntimeException: Unable to pause activity {com.knopka/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter)' on a null object reference
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3388)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3347)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3322)
	at android.app.ActivityThread.access$1100(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5442)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter)' on a null object reference
	at com.github.yamill.orientation.OrientationModule.onHostResume(OrientationModule.java:150)
	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:187)
	at com.facebook.react.ReactInstanceManager.moveToBeforeResumeLifecycleState(ReactInstanceManager.java:565)
	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:442)
	at com.reactnativenavigation.react.NavigationReactGateway.onPauseActivity(NavigationReactGateway.java:72)
	at com.reactnativenavigation.controllers.NavigationActivity.onPause(NavigationActivity.java:137)
	at android.app.Activity.performPause(Activity.java:6415)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1312)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3374)
	... 10 more

**Comment by stoneman1** [comment]
Can you test #202 if that fixes it?

**Comment by andrerfneves** [comment]
Could also be related to `react-native-navigation` implementation with `react-native-orientation`. Try #202 like @stoneman1 said and we can try and debug.

**Comment by ajwhite** [comment]
☝️ the start of the stack begins at `com.reactnativenavigation.controllers.NavigationActivity`, this is unrelated to `react-native-orientation`.
