### ISSUE TITLE
[Android] reload js crash

### ISSUE THREAD

**Issue by skv-headless** [yamill/react-native-orientation#30]
React Native v0.17
```
15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime: FATAL EXCEPTION: main
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime: Process: com.smarthome, PID: 13632
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime: java.lang.IllegalArgumentException: Receiver not registered: com.github.yamill.orientation.OrientationModule$1@2443df15
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:763)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1697)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:517)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.github.yamill.orientation.OrientationModule$2.onHostDestroy(OrientationModule.java:63)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.bridge.ReactContext.onDestroy(ReactContext.java:160)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:595)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:78)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:161)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.os.AsyncTask.execute(AsyncTask.java:535)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:526)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:510)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:78)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:114)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.facebook.react.devsupport.DevSupportManager$15$1.run(DevSupportManager.java:575)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5253)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
01-12 15:50:00.451 13632-13632/com.smarthome E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
```

**Comment by jpgarcia** [comment]
I'm experiencing the same issue, You can find more info about it here. https://github.com/yamill/react-native-orientation/issues/16

There is a fork with a solution created by @vitaminwater here => https://github.com/vitaminwater/react-native-orientation, so you can temporary reference your npm like this:

```
"react-native-orientation": "git@github.com:vitaminwater/react-native-orientation.git#8b3f541b923d426df1c2274d76a8ec541cb4a2f1",
``` 

@vitaminwater are you going to submit a  PR with your fix?

**Comment by vitaminwater** [comment]
I just submitted a PR.

**Comment by jpgarcia** [comment]
nice!

**Comment by yamill** [comment]
just pushed to npm

**Comment by cooperka** [comment]
@yamill I'm also getting this issue. It looks like the fix was reverted... can you please explain why? https://github.com/yamill/react-native-orientation/pull/33

**Comment by johndanek** [comment]
I can confirm that I am seeing this issue, but only when building a release APK on Android.

**Comment by andrerfneves** [comment]
@johndanek what version of the package and of RN are you using?

**Comment by johndanek** [comment]
I'm directly pulling from the git source for the orientation package, and using react-native 0.45.1

I think I'm seeing this error when the app crashes for a different reason, and the receiver is lingering.

**Comment by stwiname** [comment]
I'm experiencing the same problem with v2.10 and react-native 0.45.1 in production builds. I have updated to v3.1.0

I'll report back if the issue still exists

**Comment by bacancy-swaroopa** [comment]
Hi I am also getting sam error:

  "react": "^16.0.0-alpha.6",
    "react-native": "^0.43.3",
 "react-native-orientation": "git+https://github.com/jedt/react-native-orientation.git",

Can u tell me how to solve this
