### ISSUE TITLE
Automatic Linking using react-native link react-native-orientation not working!!

### ISSUE THREAD

**Issue by Zabi-Progton** [yamill/react-native-orientation#329]
camera react-native link react-native-orientation

module.js:550
    throw err;
    ^

Error: Cannot find module 'asap/raw'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mac/Desktop/camera/node_modules/promise/lib/core.js:3:12)
    at Module._compile (module.js:653:30)
    at Module._compile (/Users/mac/Desktop/camera/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (/Users/mac/Desktop/camera/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:566:32)

**Comment by retyui** [comment]
This repo dead , use the fork https://github.com/wonday/react-native-orientation-lockera

**Comment by SergiOnGit** [comment]
This isn't plugin error. Just run yarn or npm install
