### ISSUE TITLE
Android crash: java.lang.IllegalArgumentException: Receiver not registered

### ISSUE THREAD

**Issue by sahas-** [yamill/react-native-orientation#34]
Hi,
I'm a newbie Android developer, wanted to lock down orientation on my react-native app. After implementing this module, App crashes on reload and seeing below error in the log. 
I did verify by completely removing this module and don't see App crashing anymore. Any suggestions?

- Device: SAMSUNG-SGH-I337 - 5.0.1
- React-Native: 0.1.7

In my .js code, I've this

``` 
  _orientationDidChange:function(orientation){
    console.log('orientation change');
  },
  componentDidMount: function(){
    Orientation.addOrientationListener(this._orientationDidChange);
    Orientation.lockToPortrait();
  },
  componentWillUnmount: function() {
    Orientation.removeOrientationListener(this._orientationDidChange);    
  }, 
```

```

E/AndroidRuntime(27863): FATAL EXCEPTION: main
E/AndroidRuntime(27863): Process: com.helloworld, PID: 27863
E/AndroidRuntime(27863): java.lang.IllegalArgumentException: Receiver not registered: com.github.yamill.orientation.OrientationModule$1@5a2ced3
E/AndroidRuntime(27863):  at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:822)
E/AndroidRuntime(27863):  at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:2038)
E/AndroidRuntime(27863):  at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:528)
E/AndroidRuntime(27863):  at com.github.yamill.orientation.OrientationModule$2.onHostDestroy(OrientationModule.java:63)
E/AndroidRuntime(27863):  at com.facebook.react.bridge.ReactContext.onDestroy(ReactContext.java:160)
E/AndroidRuntime(27863):  at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:595)
E/AndroidRuntime(27863):  at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:78)
E/AndroidRuntime(27863):  at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:161)
E/AndroidRuntime(27863):  at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
E/AndroidRuntime(27863):  at android.os.AsyncTask.execute(AsyncTask.java:535)
E/AndroidRuntime(27863):  at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:526)
E/AndroidRuntime(27863):  at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:510)
E/AndroidRuntime(27863):  at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:78)
E/AndroidRuntime(27863):  at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:114)
E/AndroidRuntime(27863):  at com.facebook.react.devsupport.DevSupportManager$15$1.run(DevSupportManager.java:575)
E/AndroidRuntime(27863):  at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(27863):  at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(27863):  at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(27863):  at android.app.ActivityThread.main(ActivityThread.java:5951)
E/AndroidRuntime(27863):  at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27863):  at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(27863):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)

```

**Comment by yamill** [comment]
Did you resolve this by any chance? I think someone submitted a fix for this.

**Comment by halissonvit** [comment]
I am facing the same issue... Tried with the latest release and with the master branch.

**Comment by halissonvit** [comment]
To give more context on this.
It only happens to me on react-native version 0.19.0
It works just fine on version 0.18.0

**Comment by KenChoi1992** [comment]
Probably same problem here:
`E/unknown:React: receiver already unregistered
                                                java.lang.IllegalArgumentException: Receiver not registered: com.github.yamill.orientation.OrientationModule$1@3e8207ef
                                                    at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:760)
                                                    at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1668)
                                                    at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:510)
                                                    at com.github.yamill.orientation.OrientationModule$2.onHostDestroy(OrientationModule.java:76)
                                                    at com.facebook.react.bridge.ReactContext.onDestroy(ReactContext.java:160)
                                                    at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:691)
                                                    at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:91)
                                                    at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:174)
                                                    at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
                                                    at android.os.AsyncTask.execute(AsyncTask.java:535)
                                                    at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:622)
                                                    at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:605)
                                                    at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:91)
                                                    at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:128)
                                                    at com.facebook.react.devsupport.DevSupportManagerImpl$16$1.run(DevSupportManagerImpl.java:610)
                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:135)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

**Comment by ncnlinh** [comment]
same problem here...

**Comment by ncnlinh** [comment]
App crashes if the listeners are initialized too early. We can refer to this, which solves the bug https://github.com/walmartreact/react-native-orientation-listener/pull/9

**Comment by ncnlinh** [comment]
https://github.com/walmartreact/react-native-orientation-listener/issues/8
